// ImageNet(MobileNet classify()の出力)クラス名 → アプリのカテゴリ/日本語品名 マッピング表。
//
// 各ルール: { kw: ['英語キーワード(小文字)', ...], category: '衣類', name: 'シャツ' }
// className を小文字化し、いずれかの kw が部分一致(className.includes(kw))したら採用。
// 配列の先頭から評価し最初にヒットしたルールを使う。name を省略した場合は category のみ採用する。
export const LABEL_RULES = [
  // ---------- 衣類 ----------
  { kw: ['jersey'], category: '衣類', name: 'Tシャツ' },
  { kw: ['sweatshirt'], category: '衣類', name: 'スウェット' },
  { kw: ['cardigan'], category: '衣類', name: 'カーディガン' },
  { kw: ['suit of clothes', 'suit,'], category: '衣類', name: 'スーツ' },
  { kw: ['kimono'], category: '衣類', name: '着物' },
  { kw: ['trench coat'], category: '衣類', name: 'コート' },
  { kw: ['fur coat'], category: '衣類', name: 'コート' },
  { kw: ['lab coat'], category: '衣類', name: '白衣' },
  { kw: ['jean', 'blue jean', 'denim'], category: '衣類', name: 'ジーンズ' },
  { kw: ['miniskirt', 'overskirt', 'hoopskirt', 'crinoline'], category: '衣類', name: 'スカート' },
  { kw: ['sarong'], category: '衣類', name: 'サロン' },
  { kw: ['sock'], category: '衣類', name: '靴下' },
  { kw: ['tie,', 'bow tie', 'bowtie', 'windsor tie', 'necktie'], category: '衣類', name: 'ネクタイ' },
  { kw: ['sombrero'], category: '衣類', name: '帽子' },
  { kw: ['cowboy hat', 'ten-gallon hat'], category: '衣類', name: '帽子' },
  { kw: ['bonnet', 'poke bonnet'], category: '衣類', name: '帽子' },
  { kw: ['shower cap'], category: '衣類', name: '帽子' },
  { kw: ['mitten'], category: '衣類', name: '手袋' },
  { kw: ['apron'], category: '衣類', name: 'エプロン' },
  { kw: ['diaper'], category: '衣類', name: 'おむつ' },
  { kw: ['maillot', 'swimsuit', 'bathing suit', 'swimming trunks'], category: '衣類', name: '水着' },
  { kw: ['abaya'], category: '衣類', name: '衣類' },
  { kw: ['academic gown', 'academic robe'], category: '衣類', name: 'ガウン' },
  { kw: ['military uniform'], category: '衣類', name: '制服' },
  { kw: ['pajama', 'pyjama'], category: '衣類', name: 'パジャマ' },
  { kw: ['gown'], category: '衣類', name: 'ドレス' },
  { kw: ['poncho'], category: '衣類', name: 'ポンチョ' },
  { kw: ['vestment'], category: '衣類', name: '衣類' },
  { kw: ['cloak'], category: '衣類', name: 'マント' },

  // ---------- 靴 ----------
  { kw: ['running shoe'], category: '靴', name: 'スニーカー' },
  { kw: ['loafer'], category: '靴', name: 'ローファー' },
  { kw: ['sandal'], category: '靴', name: 'サンダル' },
  { kw: ['clog'], category: '靴', name: 'サボ' },
  { kw: ['cowboy boot'], category: '靴', name: 'ブーツ' },
  { kw: ['ski boot'], category: '靴', name: 'ブーツ' },
  { kw: ['boot'], category: '靴', name: 'ブーツ' },

  // ---------- バッグ ----------
  { kw: ['backpack', 'rucksack', 'knapsack', 'packsack', 'haversack'], category: 'バッグ', name: 'リュック' },
  { kw: ['purse'], category: 'バッグ', name: 'ハンドバッグ' },
  { kw: ['wallet', 'billfold', 'notecase'], category: 'バッグ', name: '財布' },
  { kw: ['suitcase'], category: 'バッグ', name: 'スーツケース' },
  { kw: ['mailbag', 'postbag'], category: 'バッグ', name: 'バッグ' },
  { kw: ['sleeping bag'], category: 'バッグ', name: '寝袋' },
  { kw: ['plastic bag'], category: 'バッグ', name: '袋' },

  // ---------- 本 ----------
  { kw: ['book jacket', 'dust cover', 'dust jacket', 'dust wrapper'], category: '本', name: '本' },
  { kw: ['comic book'], category: '本', name: 'マンガ' },

  // ---------- 書類 ----------
  { kw: ['binder', 'ring-binder'], category: '書類', name: 'ファイル' },
  { kw: ['envelope'], category: '書類', name: '封筒' },
  { kw: ['menu'], category: '書類', name: '書類' },
  { kw: ['packet'], category: '書類', name: '書類' },
  { kw: ['file,', 'file cabinet', 'filing cabinet'], category: '書類', name: 'ファイル' },

  // ---------- ガジェット ----------
  { kw: ['laptop'], category: 'ガジェット', name: 'ノートパソコン' },
  { kw: ['notebook computer'], category: 'ガジェット', name: 'ノートパソコン' },
  { kw: ['cellular telephone', 'cellular phone', 'cellphone', 'mobile phone'], category: 'ガジェット', name: 'スマートフォン' },
  { kw: ['desktop computer'], category: 'ガジェット', name: 'デスクトップパソコン' },
  { kw: ['monitor'], category: 'ガジェット', name: 'モニター' },
  { kw: ['computer mouse', 'mouse,'], category: 'ガジェット', name: 'マウス' },
  { kw: ['computer keyboard', 'keypad'], category: 'ガジェット', name: 'キーボード' },
  { kw: ['remote control', 'remote,'], category: 'ガジェット', name: 'リモコン' },
  { kw: ['ipod'], category: 'ガジェット', name: '音楽プレーヤー' },
  { kw: ['digital watch'], category: 'ガジェット', name: 'デジタル時計' },
  { kw: ['analog watch'], category: 'ガジェット', name: '腕時計' },
  { kw: ['reflex camera'], category: 'ガジェット', name: 'カメラ' },
  { kw: ['polaroid camera', 'polaroid'], category: 'ガジェット', name: 'カメラ' },
  { kw: ['printer'], category: 'ガジェット', name: 'プリンター' },
  { kw: ['modem'], category: 'ガジェット', name: 'モデム' },
  { kw: ['hard disc', 'hard disk'], category: 'ガジェット', name: 'ハードディスク' },
  { kw: ['joystick'], category: 'ガジェット', name: 'ジョイスティック' },
  { kw: ['cassette player'], category: 'ガジェット', name: 'カセットプレーヤー' },
  { kw: ['tape player'], category: 'ガジェット', name: 'テーププレーヤー' },
  { kw: ['cd player'], category: 'ガジェット', name: 'CDプレーヤー' },
  { kw: ['radio,', 'wireless,'], category: 'ガジェット', name: 'ラジオ' },
  { kw: ['projector'], category: 'ガジェット', name: 'プロジェクター' },
  { kw: ['tablet'], category: 'ガジェット', name: 'タブレット' },
  { kw: ['dial telephone', 'dial phone', 'pay-phone', 'pay-station'], category: 'ガジェット', name: '電話機' },

  // ---------- キッチン ----------
  { kw: ['coffee mug'], category: 'キッチン', name: 'マグカップ' },
  { kw: ['cup,'], category: 'キッチン', name: 'カップ' },
  { kw: ['teapot'], category: 'キッチン', name: 'ティーポット' },
  { kw: ['caldron', 'cauldron'], category: 'キッチン', name: '鍋' },
  { kw: ['frying pan', 'frypan', 'skillet'], category: 'キッチン', name: 'フライパン' },
  { kw: ['wok'], category: 'キッチン', name: '中華鍋' },
  { kw: ['spatula'], category: 'キッチン', name: 'へら' },
  { kw: ['plate,', 'plate rack'], category: 'キッチン', name: '皿' },
  { kw: ['mixing bowl'], category: 'キッチン', name: 'ボウル' },
  { kw: ['soup bowl'], category: 'キッチン', name: 'どんぶり' },
  { kw: ['water bottle'], category: 'キッチン', name: '水筒' },
  { kw: ['pop bottle', 'soda bottle'], category: 'キッチン', name: 'ペットボトル' },
  { kw: ['wine bottle'], category: 'キッチン', name: 'ワインボトル' },
  { kw: ['beer bottle'], category: 'キッチン', name: '瓶' },
  { kw: ['corkscrew', 'bottle screw'], category: 'キッチン', name: '栓抜き' },
  { kw: ['toaster'], category: 'キッチン', name: 'トースター' },
  { kw: ['microwave'], category: 'キッチン', name: '電子レンジ' },
  { kw: ['refrigerator', 'icebox'], category: 'キッチン', name: '冷蔵庫' },
  { kw: ['dishwasher', 'dish washer'], category: 'キッチン', name: '食洗機' },
  { kw: ['espresso maker', 'espresso'], category: 'キッチン', name: 'コーヒーメーカー' },
  { kw: ['coffeepot'], category: 'キッチン', name: 'コーヒーポット' },
  { kw: ['ladle'], category: 'キッチン', name: 'おたま' },
  { kw: ['strainer'], category: 'キッチン', name: 'ザル' },
  { kw: ['cleaver', 'meat cleaver'], category: 'キッチン', name: '包丁' },
  { kw: ['can opener', 'tin opener'], category: 'キッチン', name: '缶切り' },
  { kw: ['waffle iron'], category: 'キッチン', name: 'ワッフルメーカー' },
  { kw: ['rotisserie'], category: 'キッチン', name: '調理器具' },

  // ---------- 日用品 ----------
  { kw: ['soap dispenser'], category: '日用品', name: 'ソープディスペンサー' },
  { kw: ['lotion'], category: '日用品', name: 'ローション' },
  { kw: ['sunscreen', 'sunblock'], category: '日用品', name: '日焼け止め' },
  { kw: ['paper towel'], category: '日用品', name: 'キッチンペーパー' },
  { kw: ['bath towel'], category: '日用品', name: 'タオル' },
  { kw: ['umbrella'], category: '日用品', name: '傘' },
  { kw: ['broom'], category: '日用品', name: 'ほうき' },
  { kw: ['bucket', 'pail'], category: '日用品', name: 'バケツ' },
  { kw: ['vacuum'], category: '日用品', name: '掃除機' },
  { kw: ['pillow'], category: '日用品', name: '枕' },
  { kw: ['quilt', 'comforter'], category: '日用品', name: '布団' },
  { kw: ['washbasin', 'washbowl', 'basin,', 'lavatory'], category: '日用品', name: '洗面器' },
  { kw: ['toilet tissue', 'toilet paper', 'bathroom tissue'], category: '日用品', name: 'トイレットペーパー' },
  { kw: ['handkerchief'], category: '日用品', name: 'ハンカチ' },
  { kw: ['candle', 'taper', 'wax light'], category: '日用品', name: 'ろうそく' },
  { kw: ['ballpoint'], category: '日用品', name: 'ボールペン' },
  { kw: ['fountain pen'], category: '日用品', name: '万年筆' },
  { kw: ['pencil box', 'pencil case'], category: '日用品', name: 'ペンケース' },
  { kw: ['pencil sharpener'], category: '日用品', name: '鉛筆削り' },
  { kw: ['analog clock', 'wall clock'], category: '日用品', name: '時計' },
  { kw: ['safety pin'], category: '日用品', name: '安全ピン' },
  { kw: ['band aid'], category: '日用品', name: '絆創膏' },
  { kw: ['diaper'], category: '日用品', name: 'おむつ' },

  // ---------- 家具 ----------
  { kw: ['rocking chair', 'rocker'], category: '家具', name: '椅子' },
  { kw: ['folding chair'], category: '家具', name: '椅子' },
  { kw: ['barber chair'], category: '家具', name: '椅子' },
  { kw: ['studio couch', 'day bed'], category: '家具', name: 'ソファ' },
  { kw: ['dining table', 'board,'], category: '家具', name: 'テーブル' },
  { kw: ['desk'], category: '家具', name: '机' },
  { kw: ['wardrobe', 'closet', 'press,'], category: '家具', name: 'クローゼット' },
  { kw: ['chiffonier', 'commode'], category: '家具', name: 'タンス' },
  { kw: ['bookcase'], category: '家具', name: '本棚' },
  { kw: ['table lamp'], category: '家具', name: 'ランプ' },
  { kw: ['lampshade', 'lamp shade'], category: '家具', name: 'ランプシェード' },
  { kw: ['crib', 'cot'], category: '家具', name: 'ベビーベッド' },
  { kw: ['four-poster'], category: '家具', name: 'ベッド' },
  { kw: ['china cabinet', 'china closet'], category: '家具', name: '食器棚' },

  // ---------- 趣味 ----------
  { kw: ['acoustic guitar'], category: '趣味', name: 'ギター' },
  { kw: ['electric guitar'], category: '趣味', name: 'ギター' },
  { kw: ['banjo'], category: '趣味', name: 'バンジョー' },
  { kw: ['violin', 'fiddle'], category: '趣味', name: 'バイオリン' },
  { kw: ['tennis racket', 'tennis racquet', 'racket', 'racquet'], category: '趣味', name: 'テニスラケット' },
  { kw: ['basketball'], category: '趣味', name: 'バスケットボール' },
  { kw: ['soccer ball'], category: '趣味', name: 'サッカーボール' },
  { kw: ['volleyball'], category: '趣味', name: 'バレーボール' },
  { kw: ['rugby ball'], category: '趣味', name: 'ラグビーボール' },
  { kw: ['baseball'], category: '趣味', name: '野球ボール' },
  { kw: ['golf ball'], category: '趣味', name: 'ゴルフボール' },
  { kw: ['punching bag', 'punch bag'], category: '趣味', name: 'サンドバッグ' },
  { kw: ['dumbbell'], category: '趣味', name: 'ダンベル' },
  { kw: ['barbell'], category: '趣味', name: 'バーベル' },
  { kw: ['ski,', 'skis'], category: '趣味', name: 'スキー板' },
  { kw: ['skateboard'], category: '趣味', name: 'スケートボード' },
  { kw: ['mountain bike', 'all-terrain bike'], category: '趣味', name: '自転車' },
  { kw: ['bicycle-built-for-two', 'tandem bicycle', 'tandem'], category: '趣味', name: '自転車' },
  { kw: ['teddy', 'teddy bear'], category: '趣味', name: 'ぬいぐるみ' },
  { kw: ['fishing rod', 'fishing pole'], category: '趣味', name: '釣り竿' },
  { kw: ['paddle,', 'boat paddle'], category: '趣味', name: 'パドル' },
  { kw: ['chess'], category: '趣味', name: 'チェスセット' },
  { kw: ['jigsaw puzzle'], category: '趣味', name: 'パズル' },
  { kw: ['harmonica', 'mouth organ'], category: '趣味', name: 'ハーモニカ' },
  { kw: ['accordion'], category: '趣味', name: 'アコーディオン' },

  // ---------- 美容 ----------
  { kw: ['hair spray'], category: '美容', name: 'ヘアスプレー' },
  { kw: ['perfume', 'essence'], category: '美容', name: '香水' },
  { kw: ['lipstick', 'lip rouge'], category: '美容', name: '口紅' },
  { kw: ['hair slide'], category: '美容', name: 'ヘアピン' },
  { kw: ['sunglasses', 'sunglass', 'dark glasses', 'shades'], category: '美容', name: 'サングラス' },
  { kw: ['face powder'], category: '美容', name: 'フェイスパウダー' },
  { kw: ['hand blower', 'blow dryer', 'blow drier', 'hair dryer'], category: '美容', name: 'ドライヤー' },
  { kw: ['bath cap', 'shower cap'], category: '美容', name: 'シャワーキャップ' },

  // ---------- 追加ルール(端末内AI精度向上・ImageNet-1kクラスから拡充) ----------

  // ---------- 日用品(文具・工具・収納・家庭雑貨) ----------
  { kw: ['rubber eraser'], category: '日用品', name: '消しゴム' },
  { kw: ['quill'], category: '日用品', name: '羽根ペン' },
  { kw: ['hammer'], category: '日用品', name: '金づち' },
  { kw: ['screwdriver'], category: '日用品', name: 'ドライバー' },
  { kw: ['power drill'], category: '日用品', name: '電動ドリル' },
  { kw: ['hatchet'], category: '日用品', name: '手斧' },
  { kw: ["carpenter's plane", 'woodworking plane'], category: '日用品', name: 'かんな' },
  { kw: ['chain saw', 'chainsaw'], category: '日用品', name: 'チェーンソー' },
  { kw: ['shovel'], category: '日用品', name: 'シャベル' },
  { kw: ['screw'], category: '日用品', name: 'ねじ' },
  { kw: ['padlock'], category: '日用品', name: '南京錠' },
  { kw: ["carpenter's kit", 'tool kit'], category: '日用品', name: '工具箱' },
  { kw: ['lighter'], category: '日用品', name: 'ライター' },
  { kw: ['matchstick'], category: '日用品', name: 'マッチ' },
  { kw: ['pill bottle'], category: '日用品', name: '薬の容器' },
  { kw: ['binoculars'], category: '日用品', name: '双眼鏡' },
  { kw: ['loupe'], category: '日用品', name: 'ルーペ' },
  { kw: ['torch'], category: '日用品', name: '懐中電灯' },
  { kw: ['birdhouse'], category: '日用品', name: '巣箱' },
  { kw: ['flowerpot'], category: '日用品', name: '植木鉢' },
  { kw: ['mailbox'], category: '日用品', name: '郵便受け' },
  { kw: ['doormat'], category: '日用品', name: '玄関マット' },
  { kw: ['window shade'], category: '日用品', name: 'ロールスクリーン' },
  { kw: ['balloon'], category: '日用品', name: '風船' },
  { kw: ['swing'], category: '日用品', name: 'ブランコ' },
  { kw: ['mosquito net'], category: '日用品', name: '蚊帳' },
  { kw: ['fire screen'], category: '日用品', name: '暖炉用スクリーン' },
  { kw: ['radiator'], category: '日用品', name: '暖房器具' },
  { kw: ['medicine chest', 'medicine cabinet'], category: '日用品', name: '救急箱' },
  { kw: ['safe'], category: '日用品', name: '金庫' },
  { kw: ['hamper'], category: '日用品', name: '洗濯かご' },
  { kw: ['trash can', 'ashcan', 'wastebin'], category: '日用品', name: 'ゴミ箱' },
  { kw: ['barrel'], category: '日用品', name: '樽' },
  { kw: ['shopping basket'], category: '日用品', name: '買い物かご' },
  { kw: ['crate'], category: '日用品', name: '木箱' },
  { kw: ['vase'], category: '日用品', name: '花瓶' },
  { kw: ['digital clock'], category: '日用品', name: 'デジタル時計' },
  { kw: ['stopwatch', 'stop watch'], category: '日用品', name: 'ストップウォッチ' },
  { kw: ['space heater'], category: '日用品', name: 'ヒーター' },
  { kw: ['electric fan'], category: '日用品', name: '扇風機' },
  { kw: ['smoothing iron'], category: '日用品', name: 'アイロン' },
  { kw: ['washing machine'], category: '日用品', name: '洗濯機' },
  { kw: ['sewing machine'], category: '日用品', name: 'ミシン' },
  { kw: ['barometer'], category: '日用品', name: '気圧計' },
  { kw: ['wheelbarrow'], category: '日用品', name: '手押し車' },
  { kw: ['carton'], category: '日用品', name: '段ボール箱' },
  { kw: ['christmas stocking'], category: '日用品', name: 'クリスマスストッキング' },
  { kw: ['combination lock'], category: '日用品', name: 'ダイヤル錠' },
  { kw: ['crutch'], category: '日用品', name: '松葉杖' },
  { kw: ['hourglass'], category: '日用品', name: '砂時計' },
  { kw: ['lawn mower'], category: '日用品', name: '芝刈り機' },
  { kw: ['letter opener'], category: '日用品', name: 'レターオープナー' },
  { kw: ['mousetrap'], category: '日用品', name: 'ねずみ捕り' },
  { kw: ['piggy bank'], category: '日用品', name: '貯金箱' },
  { kw: ['plunger'], category: '日用品', name: 'ラバーカップ' },
  { kw: ['ruler'], category: '日用品', name: '定規' },
  { kw: ['weighing machine'], category: '日用品', name: '秤' },
  { kw: ['shower curtain'], category: '日用品', name: 'シャワーカーテン' },
  { kw: ['stethoscope'], category: '日用品', name: '聴診器' },
  { kw: ['toilet seat'], category: '日用品', name: '便座' },
  { kw: ['thimble'], category: '日用品', name: '指ぬき' },

  // ---------- キッチン(追加) ----------
  { kw: ['goblet'], category: 'キッチン', name: 'ゴブレット' },
  { kw: ['beer glass'], category: 'キッチン', name: 'ビアグラス' },
  { kw: ['pitcher', 'ewer'], category: 'キッチン', name: '水差し' },
  { kw: ['tray'], category: 'キッチン', name: 'トレー' },
  { kw: ['saltshaker', 'salt shaker'], category: 'キッチン', name: '塩入れ' },
  { kw: ['measuring cup'], category: 'キッチン', name: '計量カップ' },
  { kw: ['cocktail shaker'], category: 'キッチン', name: 'カクテルシェーカー' },
  { kw: ['dutch oven'], category: 'キッチン', name: '鋳物鍋' },
  { kw: ['wooden spoon'], category: 'キッチン', name: '木べら' },
  { kw: ['whiskey jug'], category: 'キッチン', name: 'ジャグ' },
  { kw: ['water jug'], category: 'キッチン', name: 'ウォータージャグ' },
  { kw: ['crock pot'], category: 'キッチン', name: 'スロークッカー' },
  { kw: ['stove'], category: 'キッチン', name: 'コンロ' },
  { kw: ['dishrag', 'dishcloth'], category: 'キッチン', name: 'ふきん' },

  // ---------- ガジェット(追加) ----------
  { kw: ['television'], category: 'ガジェット', name: 'テレビ' },
  { kw: ['loudspeaker'], category: 'ガジェット', name: 'スピーカー' },
  { kw: ['microphone'], category: 'ガジェット', name: 'マイク' },
  { kw: ['lens cap'], category: 'ガジェット', name: 'レンズキャップ' },
  { kw: ['photocopier'], category: 'ガジェット', name: 'コピー機' },
  { kw: ['home theater', 'home theatre'], category: 'ガジェット', name: 'ホームシアター' },

  // ---------- 家具(追加) ----------
  { kw: ['chest'], category: '家具', name: '収納箱' },
  { kw: ['cradle'], category: '家具', name: 'ゆりかご' },
  { kw: ['bassinet'], category: '家具', name: 'バシネット' },
  { kw: ['entertainment center'], category: '家具', name: 'テレビ台' },
  { kw: ['shoji'], category: '家具', name: '障子' },
  { kw: ['window screen'], category: '家具', name: '網戸' },
  { kw: ['spotlight'], category: '家具', name: 'スポットライト' },

  // ---------- 趣味(楽器・スポーツ・乗り物・その他ホビー、追加) ----------
  { kw: ['grand piano'], category: '趣味', name: 'グランドピアノ' },
  { kw: ['upright piano'], category: '趣味', name: 'アップライトピアノ' },
  { kw: ['flute'], category: '趣味', name: 'フルート' },
  { kw: ['trombone'], category: '趣味', name: 'トロンボーン' },
  { kw: ['saxophone'], category: '趣味', name: 'サックス' },
  { kw: ['cello'], category: '趣味', name: 'チェロ' },
  { kw: ['drum,'], category: '趣味', name: 'ドラム' },
  { kw: ['drumstick'], category: '趣味', name: 'ドラムスティック' },
  { kw: ['maraca'], category: '趣味', name: 'マラカス' },
  { kw: ['ocarina'], category: '趣味', name: 'オカリナ' },
  { kw: ['harp'], category: '趣味', name: 'ハープ' },
  { kw: ['snorkel'], category: '趣味', name: 'シュノーケル' },
  { kw: ['ping-pong ball'], category: '趣味', name: '卓球ボール' },
  { kw: ['puck'], category: '趣味', name: 'アイスホッケーパック' },
  { kw: ['mountain tent'], category: '趣味', name: 'テント' },
  { kw: ['unicycle'], category: '趣味', name: '一輪車' },
  { kw: ['tricycle'], category: '趣味', name: '三輪車' },
  { kw: ['motor scooter', 'scooter'], category: '趣味', name: 'スクーター' },
  { kw: ['moped'], category: '趣味', name: 'モペット' },
  { kw: ['crash helmet'], category: '趣味', name: 'ヘルメット' },
  { kw: ['football helmet'], category: '趣味', name: 'アメフト用ヘルメット' },
  { kw: ['abacus'], category: '趣味', name: 'そろばん' },
  { kw: ['canoe'], category: '趣味', name: 'カヌー' },
  { kw: ['cassette'], category: '趣味', name: 'カセットテープ' },
  { kw: ['trumpet'], category: '趣味', name: 'トランペット' },
  { kw: ['french horn'], category: '趣味', name: 'ホルン' },
  { kw: ['chime'], category: '趣味', name: 'チャイム' },
  { kw: ['gong'], category: '趣味', name: '銅鑼' },
  { kw: ['knee pad'], category: '趣味', name: 'ニーパッド' },
  { kw: ['magnetic compass'], category: '趣味', name: 'コンパス' },
  { kw: ['marimba', 'xylophone'], category: '趣味', name: '木琴' },
  { kw: ['oboe'], category: '趣味', name: 'オーボエ' },
  { kw: ['pipe organ'], category: '趣味', name: 'オルガン' },
  { kw: ['paintbrush'], category: '趣味', name: '絵筆' },
  { kw: ['plectrum'], category: '趣味', name: 'ピック' },
  { kw: ['pinwheel'], category: '趣味', name: '風車(おもちゃ)' },
  { kw: ['pool table', 'billiard table'], category: '趣味', name: 'ビリヤード台' },
  { kw: ['typewriter keyboard'], category: '趣味', name: 'タイプライター' },
  { kw: ['whistle'], category: '趣味', name: 'ホイッスル' },
  { kw: ['crossword'], category: '趣味', name: 'クロスワードパズル' },
  { kw: ['tennis ball'], category: '趣味', name: 'テニスボール' },

  // ---------- 衣類(追加) ----------
  { kw: ['brassiere'], category: '衣類', name: 'ブラジャー' },
  { kw: ['stole'], category: '衣類', name: 'ストール' },
  { kw: ['feather boa'], category: '衣類', name: 'フェザーボア' },
  { kw: ['buckle'], category: '衣類', name: 'バックル' },
  { kw: ['bib'], category: '衣類', name: 'よだれかけ' },
  { kw: ['bikini'], category: '衣類', name: 'ビキニ' },
  { kw: ['bolo tie'], category: '衣類', name: 'ボロタイ' },
  { kw: ['mortarboard'], category: '衣類', name: '角帽' },
  { kw: ['ski mask'], category: '衣類', name: '目出し帽' },

  // ---------- 美容(追加) ----------
  { kw: ['bathing cap'], category: '美容', name: '水泳帽' },
  { kw: ['necklace'], category: '美容', name: 'ネックレス' },
  { kw: ['wig'], category: '美容', name: 'かつら' },

  // ---------- 日用品(モペットの後段: mopedと"mop"の部分一致競合を避けるため末尾に配置) ----------
  { kw: ['mop'], category: '日用品', name: 'モップ' },
];
