// ImageNet(MobileNet classify()の出力)クラス名 → アプリのカテゴリ/日本語品名 マッピング表。
//
// 各ルール: { kw: ['英語キーワード(小文字)', ...], category: '衣類', name: 'シャツ' }
// className を小文字化し、いずれかの kw が部分一致(className.includes(kw))したら採用。
// 配列の先頭から評価し最初にヒットしたルールを使う。name を省略した場合は category のみ採用する。
export const LABEL_RULES = [
  // ---------- 衣類 ----------
  { kw: ['jersey'], category: '衣類', name: 'Tシャツ' },
  { kw: ['sweatshirt'], category: '衣類', name: 'スウェット' },
  { kw: ['cardigan'], category: '衣類', name: 'カーディガン' },
  { kw: ['suit of clothes', 'suit,'], category: '衣類', name: 'スーツ' },
  { kw: ['kimono'], category: '衣類', name: '着物' },
  { kw: ['trench coat'], category: '衣類', name: 'コート' },
  { kw: ['fur coat'], category: '衣類', name: 'コート' },
  { kw: ['lab coat'], category: '衣類', name: '白衣' },
  { kw: ['jean', 'blue jean', 'denim'], category: '衣類', name: 'ジーンズ' },
  { kw: ['miniskirt', 'overskirt', 'hoopskirt', 'crinoline'], category: '衣類', name: 'スカート' },
  { kw: ['sarong'], category: '衣類', name: 'サロン' },
  { kw: ['sock'], category: '衣類', name: '靴下' },
  { kw: ['tie,', 'bow tie', 'bowtie', 'windsor tie', 'necktie'], category: '衣類', name: 'ネクタイ' },
  { kw: ['sombrero'], category: '衣類', name: '帽子' },
  { kw: ['cowboy hat', 'ten-gallon hat'], category: '衣類', name: '帽子' },
  { kw: ['bonnet', 'poke bonnet'], category: '衣類', name: '帽子' },
  { kw: ['shower cap'], category: '衣類', name: '帽子' },
  { kw: ['mitten'], category: '衣類', name: '手袋' },
  { kw: ['apron'], category: '衣類', name: 'エプロン' },
  { kw: ['diaper'], category: '衣類', name: 'おむつ' },
  { kw: ['maillot', 'swimsuit', 'bathing suit', 'swimming trunks'], category: '衣類', name: '水着' },
  { kw: ['abaya'], category: '衣類', name: '衣類' },
  { kw: ['academic gown', 'academic robe'], category: '衣類', name: 'ガウン' },
  { kw: ['military uniform'], category: '衣類', name: '制服' },
  { kw: ['pajama', 'pyjama'], category: '衣類', name: 'パジャマ' },
  { kw: ['gown'], category: '衣類', name: 'ドレス' },
  { kw: ['poncho'], category: '衣類', name: 'ポンチョ' },
  { kw: ['vestment'], category: '衣類', name: '衣類' },
  { kw: ['cloak'], category: '衣類', name: 'マント' },

  // ---------- 靴 ----------
  { kw: ['running shoe'], category: '靴', name: 'スニーカー' },
  { kw: ['loafer'], category: '靴', name: 'ローファー' },
  { kw: ['sandal'], category: '靴', name: 'サンダル' },
  { kw: ['clog'], category: '靴', name: 'サボ' },
  { kw: ['cowboy boot'], category: '靴', name: 'ブーツ' },
  { kw: ['ski boot'], category: '靴', name: 'ブーツ' },
  { kw: ['boot'], category: '靴', name: 'ブーツ' },

  // ---------- バッグ ----------
  { kw: ['backpack', 'rucksack', 'knapsack', 'packsack', 'haversack'], category: 'バッグ', name: 'リュック' },
  { kw: ['purse'], category: 'バッグ', name: 'ハンドバッグ' },
  { kw: ['wallet', 'billfold', 'notecase'], category: 'バッグ', name: '財布' },
  { kw: ['suitcase'], category: 'バッグ', name: 'スーツケース' },
  { kw: ['mailbag', 'postbag'], category: 'バッグ', name: 'バッグ' },
  { kw: ['sleeping bag'], category: 'バッグ', name: '寝袋' },
  { kw: ['plastic bag'], category: 'バッグ', name: '袋' },

  // ---------- 本 ----------
  { kw: ['book jacket', 'dust cover', 'dust jacket', 'dust wrapper'], category: '本', name: '本' },
  { kw: ['comic book'], category: '本', name: 'マンガ' },

  // ---------- 書類 ----------
  { kw: ['binder', 'ring-binder'], category: '書類', name: 'ファイル' },
  { kw: ['envelope'], category: '書類', name: '封筒' },
  { kw: ['menu'], category: '書類', name: '書類' },
  { kw: ['packet'], category: '書類', name: '書類' },
  { kw: ['file,', 'file cabinet', 'filing cabinet'], category: '書類', name: 'ファイル' },

  // ---------- ガジェット ----------
  { kw: ['laptop'], category: 'ガジェット', name: 'ノートパソコン' },
  { kw: ['notebook computer'], category: 'ガジェット', name: 'ノートパソコン' },
  { kw: ['cellular telephone', 'cellular phone', 'cellphone', 'mobile phone'], category: 'ガジェット', name: 'スマートフォン' },
  { kw: ['desktop computer'], category: 'ガジェット', name: 'デスクトップパソコン' },
  { kw: ['monitor'], category: 'ガジェット', name: 'モニター' },
  { kw: ['computer mouse', 'mouse,'], category: 'ガジェット', name: 'マウス' },
  { kw: ['computer keyboard', 'keypad'], category: 'ガジェット', name: 'キーボード' },
  { kw: ['remote control', 'remote,'], category: 'ガジェット', name: 'リモコン' },
  { kw: ['ipod'], category: 'ガジェット', name: '音楽プレーヤー' },
  { kw: ['digital watch'], category: 'ガジェット', name: 'デジタル時計' },
  { kw: ['analog watch'], category: 'ガジェット', name: '腕時計' },
  { kw: ['reflex camera'], category: 'ガジェット', name: 'カメラ' },
  { kw: ['polaroid camera', 'polaroid'], category: 'ガジェット', name: 'カメラ' },
  { kw: ['printer'], category: 'ガジェット', name: 'プリンター' },
  { kw: ['modem'], category: 'ガジェット', name: 'モデム' },
  { kw: ['hard disc', 'hard disk'], category: 'ガジェット', name: 'ハードディスク' },
  { kw: ['joystick'], category: 'ガジェット', name: 'ジョイスティック' },
  { kw: ['cassette player'], category: 'ガジェット', name: 'カセットプレーヤー' },
  { kw: ['tape player'], category: 'ガジェット', name: 'テーププレーヤー' },
  { kw: ['cd player'], category: 'ガジェット', name: 'CDプレーヤー' },
  { kw: ['radio,', 'wireless,'], category: 'ガジェット', name: 'ラジオ' },
  { kw: ['projector'], category: 'ガジェット', name: 'プロジェクター' },
  { kw: ['tablet'], category: 'ガジェット', name: 'タブレット' },
  { kw: ['dial telephone', 'dial phone', 'pay-phone', 'pay-station'], category: 'ガジェット', name: '電話機' },

  // ---------- キッチン ----------
  { kw: ['coffee mug'], category: 'キッチン', name: 'マグカップ' },
  { kw: ['cup,'], category: 'キッチン', name: 'カップ' },
  { kw: ['teapot'], category: 'キッチン', name: 'ティーポット' },
  { kw: ['caldron', 'cauldron'], category: 'キッチン', name: '鍋' },
  { kw: ['frying pan', 'frypan', 'skillet'], category: 'キッチン', name: 'フライパン' },
  { kw: ['wok'], category: 'キッチン', name: '中華鍋' },
  { kw: ['spatula'], category: 'キッチン', name: 'へら' },
  { kw: ['plate,', 'plate rack'], category: 'キッチン', name: '皿' },
  { kw: ['mixing bowl'], category: 'キッチン', name: 'ボウル' },
  { kw: ['soup bowl'], category: 'キッチン', name: 'どんぶり' },
  { kw: ['water bottle'], category: 'キッチン', name: '水筒' },
  { kw: ['pop bottle', 'soda bottle'], category: 'キッチン', name: 'ペットボトル' },
  { kw: ['wine bottle'], category: 'キッチン', name: 'ワインボトル' },
  { kw: ['beer bottle'], category: 'キッチン', name: '瓶' },
  { kw: ['corkscrew', 'bottle screw'], category: 'キッチン', name: '栓抜き' },
  { kw: ['toaster'], category: 'キッチン', name: 'トースター' },
  { kw: ['microwave'], category: 'キッチン', name: '電子レンジ' },
  { kw: ['refrigerator', 'icebox'], category: 'キッチン', name: '冷蔵庫' },
  { kw: ['dishwasher', 'dish washer'], category: 'キッチン', name: '食洗機' },
  { kw: ['espresso maker', 'espresso'], category: 'キッチン', name: 'コーヒーメーカー' },
  { kw: ['coffeepot'], category: 'キッチン', name: 'コーヒーポット' },
  { kw: ['ladle'], category: 'キッチン', name: 'おたま' },
  { kw: ['strainer'], category: 'キッチン', name: 'ザル' },
  { kw: ['cleaver', 'meat cleaver'], category: 'キッチン', name: '包丁' },
  { kw: ['can opener', 'tin opener'], category: 'キッチン', name: '缶切り' },
  { kw: ['waffle iron'], category: 'キッチン', name: 'ワッフルメーカー' },
  { kw: ['rotisserie'], category: 'キッチン', name: '調理器具' },

  // ---------- 日用品 ----------
  { kw: ['soap dispenser'], category: '日用品', name: 'ソープディスペンサー' },
  { kw: ['lotion'], category: '日用品', name: 'ローション' },
  { kw: ['sunscreen', 'sunblock'], category: '日用品', name: '日焼け止め' },
  { kw: ['paper towel'], category: '日用品', name: 'キッチンペーパー' },
  { kw: ['bath towel'], category: '日用品', name: 'タオル' },
  { kw: ['umbrella'], category: '日用品', name: '傘' },
  { kw: ['broom'], category: '日用品', name: 'ほうき' },
  { kw: ['bucket', 'pail'], category: '日用品', name: 'バケツ' },
  { kw: ['vacuum'], category: '日用品', name: '掃除機' },
  { kw: ['pillow'], category: '日用品', name: '枕' },
  { kw: ['quilt', 'comforter'], category: '日用品', name: '布団' },
  { kw: ['washbasin', 'washbowl', 'basin,', 'lavatory'], category: '日用品', name: '洗面器' },
  { kw: ['toilet tissue', 'toilet paper', 'bathroom tissue'], category: '日用品', name: 'トイレットペーパー' },
  { kw: ['handkerchief'], category: '日用品', name: 'ハンカチ' },
  { kw: ['candle', 'taper', 'wax light'], category: '日用品', name: 'ろうそく' },
  { kw: ['ballpoint'], category: '日用品', name: 'ボールペン' },
  { kw: ['fountain pen'], category: '日用品', name: '万年筆' },
  { kw: ['pencil box', 'pencil case'], category: '日用品', name: 'ペンケース' },
  { kw: ['pencil sharpener'], category: '日用品', name: '鉛筆削り' },
  { kw: ['analog clock', 'wall clock'], category: '日用品', name: '時計' },
  { kw: ['safety pin'], category: '日用品', name: '安全ピン' },
  { kw: ['band aid'], category: '日用品', name: '絆創膏' },
  { kw: ['diaper'], category: '日用品', name: 'おむつ' },

  // ---------- 家具 ----------
  { kw: ['rocking chair', 'rocker'], category: '家具', name: '椅子' },
  { kw: ['folding chair'], category: '家具', name: '椅子' },
  { kw: ['barber chair'], category: '家具', name: '椅子' },
  { kw: ['studio couch', 'day bed'], category: '家具', name: 'ソファ' },
  { kw: ['dining table', 'board,'], category: '家具', name: 'テーブル' },
  { kw: ['desk'], category: '家具', name: '机' },
  { kw: ['wardrobe', 'closet', 'press,'], category: '家具', name: 'クローゼット' },
  { kw: ['chiffonier', 'commode'], category: '家具', name: 'タンス' },
  { kw: ['bookcase'], category: '家具', name: '本棚' },
  { kw: ['table lamp'], category: '家具', name: 'ランプ' },
  { kw: ['lampshade', 'lamp shade'], category: '家具', name: 'ランプシェード' },
  { kw: ['crib', 'cot'], category: '家具', name: 'ベビーベッド' },
  { kw: ['four-poster'], category: '家具', name: 'ベッド' },
  { kw: ['china cabinet', 'china closet'], category: '家具', name: '食器棚' },

  // ---------- 趣味 ----------
  { kw: ['acoustic guitar'], category: '趣味', name: 'ギター' },
  { kw: ['electric guitar'], category: '趣味', name: 'ギター' },
  { kw: ['banjo'], category: '趣味', name: 'バンジョー' },
  { kw: ['violin', 'fiddle'], category: '趣味', name: 'バイオリン' },
  { kw: ['tennis racket', 'tennis racquet', 'racket', 'racquet'], category: '趣味', name: 'テニスラケット' },
  { kw: ['basketball'], category: '趣味', name: 'バスケットボール' },
  { kw: ['soccer ball'], category: '趣味', name: 'サッカーボール' },
  { kw: ['volleyball'], category: '趣味', name: 'バレーボール' },
  { kw: ['rugby ball'], category: '趣味', name: 'ラグビーボール' },
  { kw: ['baseball'], category: '趣味', name: '野球ボール' },
  { kw: ['golf ball'], category: '趣味', name: 'ゴルフボール' },
  { kw: ['punching bag', 'punch bag'], category: '趣味', name: 'サンドバッグ' },
  { kw: ['dumbbell'], category: '趣味', name: 'ダンベル' },
  { kw: ['barbell'], category: '趣味', name: 'バーベル' },
  { kw: ['ski,', 'skis'], category: '趣味', name: 'スキー板' },
  { kw: ['skateboard'], category: '趣味', name: 'スケートボード' },
  { kw: ['mountain bike', 'all-terrain bike'], category: '趣味', name: '自転車' },
  { kw: ['bicycle-built-for-two', 'tandem bicycle', 'tandem'], category: '趣味', name: '自転車' },
  { kw: ['teddy', 'teddy bear'], category: '趣味', name: 'ぬいぐるみ' },
  { kw: ['fishing rod', 'fishing pole'], category: '趣味', name: '釣り竿' },
  { kw: ['paddle,', 'boat paddle'], category: '趣味', name: 'パドル' },
  { kw: ['chess'], category: '趣味', name: 'チェスセット' },
  { kw: ['jigsaw puzzle'], category: '趣味', name: 'パズル' },
  { kw: ['harmonica', 'mouth organ'], category: '趣味', name: 'ハーモニカ' },
  { kw: ['accordion'], category: '趣味', name: 'アコーディオン' },

  // ---------- 美容 ----------
  { kw: ['hair spray'], category: '美容', name: 'ヘアスプレー' },
  { kw: ['perfume', 'essence'], category: '美容', name: '香水' },
  { kw: ['lipstick', 'lip rouge'], category: '美容', name: '口紅' },
  { kw: ['hair slide'], category: '美容', name: 'ヘアピン' },
  { kw: ['sunglasses', 'sunglass', 'dark glasses', 'shades'], category: '美容', name: 'サングラス' },
  { kw: ['face powder'], category: '美容', name: 'フェイスパウダー' },
  { kw: ['hand blower', 'blow dryer', 'blow drier', 'hair dryer'], category: '美容', name: 'ドライヤー' },
  { kw: ['bath cap', 'shower cap'], category: '美容', name: 'シャワーキャップ' },
];
