// CLIP(ゼロショット画像分類)が写真と照合する語彙(=判別できる持ち物の一覧)。
//
// 各要素: { en: 'water bottle', name: '水筒', category: '日用品' }
//   en       CLIPのtext encoderに渡す自然な英語名詞(単数形)。hypothesis_template
//            ('a photo of a {}') に埋め込んで使う。
//   name     表示用の日本語一般名詞。
//   category categories.js の DEFAULT_CATEGORIES のいずれか。
//
// MobileNet(ImageNet1000クラス)に無かった日用品(水筒・リモコン・炊飯器・モバイル
// バッテリー・イヤホン・充電器・マスク・ハンガー・化粧水・シャンプー・財布・鍵など)を
// 積極的に含め、持ち物として現実的な品目を幅広くカバーする。
export const CLIP_LABELS = [
  // ---------- 衣類 ----------
  { en: 't-shirt', name: 'Tシャツ', category: '衣類' },
  { en: 'sweater', name: 'セーター', category: '衣類' },
  { en: 'hoodie', name: 'パーカー', category: '衣類' },
  { en: 'jacket', name: 'ジャケット', category: '衣類' },
  { en: 'coat', name: 'コート', category: '衣類' },
  { en: 'jeans', name: 'ジーンズ', category: '衣類' },
  { en: 'skirt', name: 'スカート', category: '衣類' },
  { en: 'dress', name: 'ワンピース', category: '衣類' },
  { en: 'suit jacket', name: 'スーツ', category: '衣類' },
  { en: 'necktie', name: 'ネクタイ', category: '衣類' },
  { en: 'scarf', name: 'マフラー', category: '衣類' },
  { en: 'gloves', name: '手袋', category: '衣類' },
  { en: 'socks', name: '靴下', category: '衣類' },
  { en: 'baseball cap', name: 'キャップ', category: '衣類' },
  { en: 'knit hat', name: 'ニット帽', category: '衣類' },
  { en: 'belt', name: 'ベルト', category: '衣類' },
  { en: 'shorts', name: '短パン', category: '衣類' },
  { en: 'cardigan', name: 'カーディガン', category: '衣類' },
  { en: 'blazer', name: 'ブレザー', category: '衣類' },
  { en: 'kimono', name: '着物', category: '衣類' },
  { en: 'swimsuit', name: '水着', category: '衣類' },
  { en: 'pajamas', name: 'パジャマ', category: '衣類' },
  { en: 'raincoat', name: 'レインコート', category: '衣類' },
  { en: 'vest', name: 'ベスト', category: '衣類' },
  { en: 'sweatpants', name: 'スウェットパンツ', category: '衣類' },
  { en: 'down jacket', name: 'ダウンジャケット', category: '衣類' },
  { en: 'windbreaker', name: 'ウィンドブレーカー', category: '衣類' },

  // ---------- 靴 ----------
  { en: 'sneakers', name: 'スニーカー', category: '靴' },
  { en: 'running shoes', name: 'ランニングシューズ', category: '靴' },
  { en: 'leather shoes', name: '革靴', category: '靴' },
  { en: 'boots', name: 'ブーツ', category: '靴' },
  { en: 'sandals', name: 'サンダル', category: '靴' },
  { en: 'loafers', name: 'ローファー', category: '靴' },
  { en: 'high heels', name: 'ハイヒール', category: '靴' },
  { en: 'slippers', name: 'スリッパ', category: '靴' },
  { en: 'flip-flops', name: 'ビーチサンダル', category: '靴' },
  { en: 'rain boots', name: 'レインブーツ', category: '靴' },
  { en: 'hiking boots', name: '登山靴', category: '靴' },
  { en: 'ballet flats', name: 'バレエシューズ', category: '靴' },
  { en: 'moccasins', name: 'モカシン', category: '靴' },
  { en: 'clogs', name: 'サボ', category: '靴' },
  { en: 'espadrilles', name: 'エスパドリーユ', category: '靴' },
  { en: 'ski boots', name: 'スキーブーツ', category: '靴' },
  { en: 'soccer cleats', name: 'サッカースパイク', category: '靴' },
  { en: 'work boots', name: 'ワークブーツ', category: '靴' },
  { en: 'ankle boots', name: 'アンクルブーツ', category: '靴' },
  { en: 'snow boots', name: 'スノーブーツ', category: '靴' },
  { en: 'platform shoes', name: '厚底シューズ', category: '靴' },
  { en: 'canvas shoes', name: 'キャンバスシューズ', category: '靴' },
  { en: 'dress shoes', name: 'ドレスシューズ', category: '靴' },
  { en: 'golf shoes', name: 'ゴルフシューズ', category: '靴' },
  { en: 'wedge sandals', name: 'ウェッジサンダル', category: '靴' },
  { en: 'house slippers', name: '部屋履き', category: '靴' },

  // ---------- バッグ ----------
  { en: 'backpack', name: 'リュック', category: 'バッグ' },
  { en: 'handbag', name: 'ハンドバッグ', category: 'バッグ' },
  { en: 'tote bag', name: 'トートバッグ', category: 'バッグ' },
  { en: 'shoulder bag', name: 'ショルダーバッグ', category: 'バッグ' },
  { en: 'wallet', name: '財布', category: 'バッグ' },
  { en: 'coin purse', name: '小銭入れ', category: 'バッグ' },
  { en: 'suitcase', name: 'スーツケース', category: 'バッグ' },
  { en: 'duffel bag', name: 'ボストンバッグ', category: 'バッグ' },
  { en: 'messenger bag', name: 'メッセンジャーバッグ', category: 'バッグ' },
  { en: 'briefcase', name: 'ブリーフケース', category: 'バッグ' },
  { en: 'clutch bag', name: 'クラッチバッグ', category: 'バッグ' },
  { en: 'waist bag', name: 'ウエストポーチ', category: 'バッグ' },
  { en: 'drawstring bag', name: '巾着袋', category: 'バッグ' },
  { en: 'garment bag', name: '洋服カバー', category: 'バッグ' },
  { en: 'laptop bag', name: 'パソコンバッグ', category: 'バッグ' },
  { en: 'diaper bag', name: 'マザーズバッグ', category: 'バッグ' },
  { en: 'gym bag', name: 'ジムバッグ', category: 'バッグ' },
  { en: 'lunch bag', name: 'ランチバッグ', category: 'バッグ' },
  { en: 'camera bag', name: 'カメラバッグ', category: 'バッグ' },
  { en: 'crossbody bag', name: 'ボディバッグ', category: 'バッグ' },
  { en: 'travel bag', name: 'トラベルバッグ', category: 'バッグ' },
  { en: 'cosmetic pouch', name: 'ポーチ', category: 'バッグ' },
  { en: 'tool bag', name: '工具バッグ', category: 'バッグ' },
  { en: 'canvas bag', name: 'キャンバスバッグ', category: 'バッグ' },
  { en: 'eco bag', name: 'エコバッグ', category: 'バッグ' },

  // ---------- 本 ----------
  { en: 'paperback book', name: '文庫本', category: '本' },
  { en: 'hardcover book', name: '単行本', category: '本' },
  { en: 'novel', name: '小説', category: '本' },
  { en: 'textbook', name: '教科書', category: '本' },
  { en: 'magazine', name: '雑誌', category: '本' },
  { en: 'comic book', name: 'コミック', category: '本' },
  { en: 'manga volume', name: 'マンガ', category: '本' },
  { en: 'picture book', name: '絵本', category: '本' },
  { en: 'dictionary', name: '辞書', category: '本' },
  { en: 'cookbook', name: 'レシピ本', category: '本' },
  { en: 'photo album', name: 'アルバム', category: '本' },
  { en: 'sketchbook', name: 'スケッチブック', category: '本' },
  { en: 'guidebook', name: 'ガイドブック', category: '本' },
  { en: 'atlas', name: '地図帳', category: '本' },
  { en: 'encyclopedia', name: '図鑑', category: '本' },
  { en: 'workbook', name: 'ドリル', category: '本' },
  { en: 'reference book', name: '参考書', category: '本' },
  { en: 'storybook', name: '童話集', category: '本' },
  { en: 'poetry book', name: '詩集', category: '本' },
  { en: 'illustrated book', name: '図解本', category: '本' },
  { en: 'business book', name: 'ビジネス書', category: '本' },
  { en: 'art book', name: '画集', category: '本' },
  { en: 'notebook', name: 'ノート', category: '本' },
  { en: 'diary', name: '日記帳', category: '本' },
  { en: 'planner', name: '手帳', category: '本' },
  { en: 'catalog', name: 'カタログ', category: '本' },

  // ---------- ガジェット ----------
  { en: 'smartphone', name: 'スマートフォン', category: 'ガジェット' },
  { en: 'laptop computer', name: 'ノートパソコン', category: 'ガジェット' },
  { en: 'tablet computer', name: 'タブレット', category: 'ガジェット' },
  { en: 'desktop computer', name: 'デスクトップパソコン', category: 'ガジェット' },
  { en: 'computer mouse', name: 'マウス', category: 'ガジェット' },
  { en: 'computer keyboard', name: 'キーボード', category: 'ガジェット' },
  { en: 'computer monitor', name: 'モニター', category: 'ガジェット' },
  { en: 'printer', name: 'プリンター', category: 'ガジェット' },
  { en: 'headphones', name: 'ヘッドホン', category: 'ガジェット' },
  { en: 'earbuds', name: 'イヤホン', category: 'ガジェット' },
  { en: 'wireless earbuds', name: 'ワイヤレスイヤホン', category: 'ガジェット' },
  { en: 'smartwatch', name: 'スマートウォッチ', category: 'ガジェット' },
  { en: 'digital camera', name: 'デジタルカメラ', category: 'ガジェット' },
  { en: 'camera tripod', name: '三脚', category: 'ガジェット' },
  { en: 'power bank', name: 'モバイルバッテリー', category: 'ガジェット' },
  { en: 'phone charger', name: '充電器', category: 'ガジェット' },
  { en: 'USB cable', name: 'USBケーブル', category: 'ガジェット' },
  { en: 'USB flash drive', name: 'USBメモリ', category: 'ガジェット' },
  { en: 'external hard drive', name: '外付けハードディスク', category: 'ガジェット' },
  { en: 'wifi router', name: 'ルーター', category: 'ガジェット' },
  { en: 'webcam', name: 'ウェブカメラ', category: 'ガジェット' },
  { en: 'microphone', name: 'マイク', category: 'ガジェット' },
  { en: 'portable speaker', name: 'スピーカー', category: 'ガジェット' },
  { en: 'game controller', name: 'ゲームコントローラー', category: 'ガジェット' },
  { en: 'handheld game console', name: '携帯ゲーム機', category: 'ガジェット' },
  { en: 'e-reader', name: '電子書籍リーダー', category: 'ガジェット' },
  { en: 'calculator', name: '電卓', category: 'ガジェット' },
  { en: 'remote control', name: 'リモコン', category: 'ガジェット' },
  { en: 'drone', name: 'ドローン', category: 'ガジェット' },
  { en: 'projector', name: 'プロジェクター', category: 'ガジェット' },
  { en: 'smart plug', name: 'スマートプラグ', category: 'ガジェット' },
  { en: 'wireless charger', name: 'ワイヤレス充電器', category: 'ガジェット' },

  // ---------- キッチン ----------
  { en: 'water bottle', name: '水筒', category: 'キッチン' },
  { en: 'thermos', name: '魔法瓶', category: 'キッチン' },
  { en: 'coffee mug', name: 'マグカップ', category: 'キッチン' },
  { en: 'tea cup', name: '湯呑み', category: 'キッチン' },
  { en: 'wine glass', name: 'ワイングラス', category: 'キッチン' },
  { en: 'drinking glass', name: 'コップ', category: 'キッチン' },
  { en: 'dinner plate', name: '皿', category: 'キッチン' },
  { en: 'rice bowl', name: '茶碗', category: 'キッチン' },
  { en: 'frying pan', name: 'フライパン', category: 'キッチン' },
  { en: 'cooking pot', name: '鍋', category: 'キッチン' },
  { en: 'kettle', name: 'やかん', category: 'キッチン' },
  { en: 'rice cooker', name: '炊飯器', category: 'キッチン' },
  { en: 'toaster', name: 'トースター', category: 'キッチン' },
  { en: 'blender', name: 'ミキサー', category: 'キッチン' },
  { en: 'kitchen knife', name: '包丁', category: 'キッチン' },
  { en: 'cutting board', name: 'まな板', category: 'キッチン' },
  { en: 'chopsticks', name: '箸', category: 'キッチン' },
  { en: 'fork', name: 'フォーク', category: 'キッチン' },
  { en: 'spoon', name: 'スプーン', category: 'キッチン' },
  { en: 'ladle', name: 'おたま', category: 'キッチン' },
  { en: 'whisk', name: '泡立て器', category: 'キッチン' },
  { en: 'spatula', name: 'フライ返し', category: 'キッチン' },
  { en: 'colander', name: 'ザル', category: 'キッチン' },
  { en: 'food storage container', name: '保存容器', category: 'キッチン' },
  { en: 'lunch box', name: '弁当箱', category: 'キッチン' },
  { en: 'can opener', name: '缶切り', category: 'キッチン' },
  { en: 'coffee maker', name: 'コーヒーメーカー', category: 'キッチン' },
  { en: 'electric kettle', name: '電気ケトル', category: 'キッチン' },
  { en: 'measuring cup', name: '計量カップ', category: 'キッチン' },
  { en: 'mixing bowl', name: 'ボウル', category: 'キッチン' },
  { en: 'baking tray', name: '天板', category: 'キッチン' },
  { en: 'bottled beverage', name: 'ペットボトル飲料', category: 'キッチン' },
  { en: 'retort pouch food', name: 'レトルト食品', category: 'キッチン' },

  // ---------- 日用品 ----------
  { en: 'tissue box', name: 'ティッシュ箱', category: '日用品' },
  { en: 'toilet paper roll', name: 'トイレットペーパー', category: '日用品' },
  { en: 'umbrella', name: '傘', category: '日用品' },
  { en: 'bath towel', name: 'タオル', category: '日用品' },
  { en: 'hand towel', name: 'ハンドタオル', category: '日用品' },
  { en: 'hair dryer', name: 'ドライヤー', category: '日用品' },
  { en: 'toothbrush', name: '歯ブラシ', category: '日用品' },
  { en: 'toothpaste tube', name: '歯磨き粉', category: '日用品' },
  { en: 'bar soap', name: '石鹸', category: '日用品' },
  { en: 'hand soap dispenser', name: 'ハンドソープ', category: '日用品' },
  { en: 'shampoo bottle', name: 'シャンプー', category: '日用品' },
  { en: 'extension cord', name: '延長コード', category: '日用品' },
  { en: 'power strip', name: '電源タップ', category: '日用品' },
  { en: 'flashlight', name: '懐中電灯', category: '日用品' },
  { en: 'battery', name: '電池', category: '日用品' },
  { en: 'alarm clock', name: '目覚まし時計', category: '日用品' },
  { en: 'wall clock', name: '掛け時計', category: '日用品' },
  { en: 'clothes hanger', name: 'ハンガー', category: '日用品' },
  { en: 'clothespin', name: '洗濯ばさみ', category: '日用品' },
  { en: 'laundry basket', name: '洗濯かご', category: '日用品' },
  { en: 'trash bag', name: 'ゴミ袋', category: '日用品' },
  { en: 'sponge', name: 'スポンジ', category: '日用品' },
  { en: 'broom', name: 'ほうき', category: '日用品' },
  { en: 'mop', name: 'モップ', category: '日用品' },
  { en: 'vacuum cleaner', name: '掃除機', category: '日用品' },
  { en: 'air freshener', name: '芳香剤', category: '日用品' },
  { en: 'humidifier', name: '加湿器', category: '日用品' },
  { en: 'electric fan', name: '扇風機', category: '日用品' },
  { en: 'space heater', name: 'ヒーター', category: '日用品' },
  { en: 'first aid kit', name: '救急箱', category: '日用品' },
  { en: 'digital thermometer', name: '体温計', category: '日用品' },
  { en: 'face mask', name: 'マスク', category: '日用品' },
  { en: 'hand sanitizer bottle', name: '消毒液', category: '日用品' },
  { en: 'sewing kit', name: '裁縫セット', category: '日用品' },
  { en: 'scissors', name: 'はさみ', category: '日用品' },
  { en: 'tape dispenser', name: 'テープカッター', category: '日用品' },
  { en: 'stapler', name: 'ホッチキス', category: '日用品' },
  { en: 'glue stick', name: 'のり', category: '日用品' },
  { en: 'ballpoint pen', name: 'ボールペン', category: '日用品' },
  { en: 'wooden pencil', name: '鉛筆', category: '日用品' },
  { en: 'sticky notes', name: '付箋', category: '日用品' },
  { en: 'ruler', name: '定規', category: '日用品' },
  { en: 'door key', name: '鍵', category: '日用品' },
  { en: 'keychain', name: 'キーホルダー', category: '日用品' },
  { en: 'lighter', name: 'ライター', category: '日用品' },
  { en: 'candle', name: 'ろうそく', category: '日用品' },

  // ---------- 家具 ----------
  { en: 'dining chair', name: '椅子', category: '家具' },
  { en: 'office chair', name: 'オフィスチェア', category: '家具' },
  { en: 'dining table', name: 'ダイニングテーブル', category: '家具' },
  { en: 'coffee table', name: 'ローテーブル', category: '家具' },
  { en: 'sofa', name: 'ソファ', category: '家具' },
  { en: 'armchair', name: 'アームチェア', category: '家具' },
  { en: 'bookshelf', name: '本棚', category: '家具' },
  { en: 'wardrobe', name: 'クローゼット', category: '家具' },
  { en: 'chest of drawers', name: 'タンス', category: '家具' },
  { en: 'bed frame', name: 'ベッドフレーム', category: '家具' },
  { en: 'mattress', name: 'マットレス', category: '家具' },
  { en: 'nightstand', name: 'ナイトテーブル', category: '家具' },
  { en: 'writing desk', name: '机', category: '家具' },
  { en: 'floor lamp', name: 'フロアランプ', category: '家具' },
  { en: 'table lamp', name: '卓上ランプ', category: '家具' },
  { en: 'curtain', name: 'カーテン', category: '家具' },
  { en: 'area rug', name: 'ラグ', category: '家具' },
  { en: 'wall mirror', name: '姿見', category: '家具' },
  { en: 'shelving unit', name: '棚', category: '家具' },
  { en: 'TV stand', name: 'テレビ台', category: '家具' },
  { en: 'shoe rack', name: '靴箱', category: '家具' },
  { en: 'coat rack', name: 'コートハンガー', category: '家具' },
  { en: 'storage box', name: '収納ボックス', category: '家具' },
  { en: 'filing cabinet', name: 'ファイルキャビネット', category: '家具' },
  { en: 'folding chair', name: '折りたたみ椅子', category: '家具' },
  { en: 'bean bag chair', name: 'ビーズクッション', category: '家具' },
  { en: 'storage ottoman', name: 'オットマン', category: '家具' },

  // ---------- 趣味 ----------
  { en: 'acoustic guitar', name: 'アコースティックギター', category: '趣味' },
  { en: 'electric guitar', name: 'エレキギター', category: '趣味' },
  { en: 'violin', name: 'バイオリン', category: '趣味' },
  { en: 'piano', name: 'ピアノ', category: '趣味' },
  { en: 'ukulele', name: 'ウクレレ', category: '趣味' },
  { en: 'drum set', name: 'ドラムセット', category: '趣味' },
  { en: 'skateboard', name: 'スケートボード', category: '趣味' },
  { en: 'bicycle', name: '自転車', category: '趣味' },
  { en: 'tennis racket', name: 'テニスラケット', category: '趣味' },
  { en: 'golf club', name: 'ゴルフクラブ', category: '趣味' },
  { en: 'baseball glove', name: 'グローブ', category: '趣味' },
  { en: 'basketball', name: 'バスケットボール', category: '趣味' },
  { en: 'soccer ball', name: 'サッカーボール', category: '趣味' },
  { en: 'yoga mat', name: 'ヨガマット', category: '趣味' },
  { en: 'dumbbell', name: 'ダンベル', category: '趣味' },
  { en: 'fishing rod', name: '釣り竿', category: '趣味' },
  { en: 'camping tent', name: 'テント', category: '趣味' },
  { en: 'sleeping bag', name: '寝袋', category: '趣味' },
  { en: 'playing cards', name: 'トランプ', category: '趣味' },
  { en: 'board game', name: 'ボードゲーム', category: '趣味' },
  { en: 'jigsaw puzzle', name: 'パズル', category: '趣味' },
  { en: 'paintbrush', name: '絵筆', category: '趣味' },
  { en: 'canvas', name: 'キャンバス', category: '趣味' },
  { en: 'knitting needles', name: '編み針', category: '趣味' },
  { en: 'yarn ball', name: '毛糸玉', category: '趣味' },
  { en: 'camera lens', name: 'カメラレンズ', category: '趣味' },
  { en: 'telescope', name: '望遠鏡', category: '趣味' },
  { en: 'binoculars', name: '双眼鏡', category: '趣味' },
  { en: 'chess set', name: 'チェスセット', category: '趣味' },
  { en: 'trading card', name: 'トレーディングカード', category: '趣味' },
  { en: 'action figure', name: 'フィギュア', category: '趣味' },
  { en: 'stuffed animal', name: 'ぬいぐるみ', category: '趣味' },
  { en: 'model kit', name: 'プラモデル', category: '趣味' },
  { en: 'snowboard', name: 'スノーボード', category: '趣味' },
  { en: 'skis', name: 'スキー板', category: '趣味' },
  { en: 'surfboard', name: 'サーフボード', category: '趣味' },
  { en: 'badminton racket', name: 'バドミントンラケット', category: '趣味' },

  // ---------- 美容 ----------
  { en: 'lipstick', name: '口紅', category: '美容' },
  { en: 'perfume bottle', name: '香水', category: '美容' },
  { en: 'makeup brush', name: '化粧筆', category: '美容' },
  { en: 'hand mirror', name: '手鏡', category: '美容' },
  { en: 'nail polish', name: 'マニキュア', category: '美容' },
  { en: 'hair straightener', name: 'ヘアアイロン', category: '美容' },
  { en: 'hair curler', name: 'カーラー', category: '美容' },
  { en: 'electric razor', name: 'シェーバー', category: '美容' },
  { en: 'cosmetic case', name: 'コスメポーチ', category: '美容' },
  { en: 'face cream jar', name: 'フェイスクリーム', category: '美容' },
  { en: 'sunscreen bottle', name: '日焼け止め', category: '美容' },
  { en: 'eyeliner', name: 'アイライナー', category: '美容' },
  { en: 'mascara', name: 'マスカラ', category: '美容' },
  { en: 'foundation bottle', name: 'ファンデーション', category: '美容' },
  { en: 'hairbrush', name: 'ヘアブラシ', category: '美容' },
  { en: 'comb', name: 'くし', category: '美容' },
  { en: 'hair clip', name: 'ヘアクリップ', category: '美容' },
  { en: 'hair tie', name: 'ヘアゴム', category: '美容' },
  { en: 'razor', name: 'カミソリ', category: '美容' },
  { en: 'tweezers', name: '毛抜き', category: '美容' },
  { en: 'nail clipper', name: '爪切り', category: '美容' },
  { en: 'facial mask sheet', name: 'フェイスパック', category: '美容' },
  { en: 'cotton pad', name: 'コットン', category: '美容' },
  { en: 'makeup palette', name: 'アイシャドウパレット', category: '美容' },
  { en: 'face roller', name: '美顔ローラー', category: '美容' },
  { en: 'hair iron', name: 'コテ', category: '美容' },
  { en: 'body lotion bottle', name: 'ボディローション', category: '美容' },

  // ---------- 書類 ----------
  { en: 'passport', name: 'パスポート', category: '書類' },
  { en: 'ring binder', name: 'バインダー', category: '書類' },
  { en: 'file folder', name: 'ファイル', category: '書類' },
  { en: 'envelope', name: '封筒', category: '書類' },
  { en: 'business card', name: '名刺', category: '書類' },
  { en: 'receipt', name: 'レシート', category: '書類' },
  { en: 'certificate', name: '証明書', category: '書類' },
  { en: 'ID card', name: 'IDカード', category: '書類' },
  { en: 'credit card', name: 'クレジットカード', category: '書類' },
  { en: 'contract document', name: '契約書', category: '書類' },
  { en: 'rubber stamp', name: 'スタンプ', category: '書類' },
  { en: 'name seal', name: '印鑑', category: '書類' },
  { en: 'stapled papers', name: '書類の束', category: '書類' },
  { en: 'sticky note pad', name: '付箋メモ', category: '書類' },
  { en: 'resume paper', name: '履歴書', category: '書類' },
  { en: 'train ticket', name: '切符', category: '書類' },
  { en: 'boarding pass', name: '搭乗券', category: '書類' },
  { en: 'invoice', name: '請求書', category: '書類' },
  { en: 'checkbook', name: '小切手帳', category: '書類' },
  { en: 'diploma', name: '卒業証書', category: '書類' },
  { en: 'postcard', name: 'はがき', category: '書類' },
  { en: 'letter', name: '手紙', category: '書類' },
  { en: 'clear file folder', name: 'クリアファイル', category: '書類' },

  // ---------- その他 ----------
  { en: 'potted plant', name: '観葉植物', category: 'その他' },
  { en: 'flower vase', name: '花瓶', category: 'その他' },
  { en: 'picture frame', name: '写真立て', category: 'その他' },
  { en: 'decorative figurine', name: '置物', category: 'その他' },
  { en: 'gift box', name: 'ギフトボックス', category: 'その他' },
  { en: 'wrapping paper roll', name: 'ラッピングペーパー', category: 'その他' },
  { en: 'shopping cart', name: 'ショッピングカート', category: 'その他' },
  { en: 'garden hose', name: 'ホース', category: 'その他' },
  { en: 'watering can', name: 'じょうろ', category: 'その他' },
  { en: 'toolbox', name: '工具箱', category: 'その他' },
  { en: 'hammer', name: '金づち', category: 'その他' },
  { en: 'screwdriver', name: 'ドライバー', category: 'その他' },
  { en: 'wrench', name: 'レンチ', category: 'その他' },
  { en: 'tape measure', name: 'メジャー', category: 'その他' },
  { en: 'electric drill', name: '電動ドリル', category: 'その他' },
  { en: 'step ladder', name: '脚立', category: 'その他' },
  { en: 'doormat', name: '玄関マット', category: 'その他' },
  { en: 'pet leash', name: 'リード', category: 'その他' },
  { en: 'dog collar', name: '首輪', category: 'その他' },
  { en: 'pet carrier', name: 'ペットキャリー', category: 'その他' },
  { en: 'birdcage', name: '鳥かご', category: 'その他' },
  { en: 'aquarium tank', name: '水槽', category: 'その他' },
  { en: 'whiteboard marker', name: 'ホワイトボードマーカー', category: 'その他' },
  { en: 'name tag', name: '名札', category: 'その他' },
  { en: 'lanyard', name: 'ストラップ', category: 'その他' },
  { en: 'sunglasses', name: 'サングラス', category: 'その他' },
  { en: 'wristwatch', name: '腕時計', category: 'その他' },
  { en: 'umbrella stand', name: '傘立て', category: 'その他' },
];
